/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms;

/**
 *
 * @author Umani Welisara
 */
public class LibraryHome_UI extends javax.swing.JFrame {

    /**
     * Creates new form LiibraryHome
     */
    public LibraryHome_UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnmanagebooks = new javax.swing.JButton();
        btnmanagemembers = new javax.swing.JButton();
        btnmanagecheckin = new javax.swing.JButton();
        btnmanagecheckin1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnmanagebooks.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnmanagebooks.setText("MANAGE BOOKS");
        btnmanagebooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanagebooksActionPerformed(evt);
            }
        });
        getContentPane().add(btnmanagebooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 390, 60));

        btnmanagemembers.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnmanagemembers.setText("MANAGE MEMBERS");
        btnmanagemembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanagemembersActionPerformed(evt);
            }
        });
        getContentPane().add(btnmanagemembers, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 390, 50));

        btnmanagecheckin.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnmanagecheckin.setText("RETURN BOOKS");
        btnmanagecheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanagecheckinActionPerformed(evt);
            }
        });
        getContentPane().add(btnmanagecheckin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 390, 60));

        btnmanagecheckin1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnmanagecheckin1.setText("BORROW BOOKS");
        btnmanagecheckin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanagecheckin1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnmanagecheckin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 390, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/library.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 320, 330));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/children-reading-book-library-looking-41465116.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 400, 410));

        setSize(new java.awt.Dimension(1196, 479));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnmanagebooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanagebooksActionPerformed
        // TODO add your handling code here:
        new Book_UI().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnmanagebooksActionPerformed

    private void btnmanagemembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanagemembersActionPerformed
        // TODO add your handling code here:
        new Member_UI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnmanagemembersActionPerformed

    private void btnmanagecheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanagecheckinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmanagecheckinActionPerformed

    private void btnmanagecheckin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanagecheckin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmanagecheckin1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryHome_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryHome_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryHome_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryHome_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryHome_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmanagebooks;
    private javax.swing.JButton btnmanagecheckin;
    private javax.swing.JButton btnmanagecheckin1;
    private javax.swing.JButton btnmanagemembers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
