/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms;

/**
 *
 * @author Umani Welisara
 */
public class LibraryHome_UI extends javax.swing.JFrame {

    /**
     * Creates new form LiibraryHome
     */
    public LibraryHome_UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnmanagebooks = new javax.swing.JButton();
        btnmanagemembers = new javax.swing.JButton();
        btnmanagecheckin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnmanagebooks.setText("MANAGE BOOKS");
        btnmanagebooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanagebooksActionPerformed(evt);
            }
        });
        getContentPane().add(btnmanagebooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 440, 60));

        btnmanagemembers.setText("MANAGE MEMBERS");
        btnmanagemembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanagemembersActionPerformed(evt);
            }
        });
        getContentPane().add(btnmanagemembers, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 440, 50));

        btnmanagecheckin.setText("MANAGE CHECKIN/OUT");
        getContentPane().add(btnmanagecheckin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 440, 60));

        setSize(new java.awt.Dimension(756, 409));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnmanagebooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanagebooksActionPerformed
        // TODO add your handling code here:
        new Book_UI().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnmanagebooksActionPerformed

    private void btnmanagemembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanagemembersActionPerformed
        // TODO add your handling code here:
        new Member_UI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnmanagemembersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryHome_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryHome_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryHome_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryHome_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryHome_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmanagebooks;
    private javax.swing.JButton btnmanagecheckin;
    private javax.swing.JButton btnmanagemembers;
    // End of variables declaration//GEN-END:variables
}
