/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Umani Welisara
 */
public class ReturnBooks_UI extends javax.swing.JFrame {

    /**
     * Creates new form ReturnBooks_UI
     */
    
    
        Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
    public ReturnBooks_UI() {
        initComponents();
        rmemid.setText("");
            rbid1.setText("");
            rbid2.setText("");
            rdayfine.setText("");
            lrtotfine.setText("N/A");
            
            conn = DBconnect.connect();
    }
    //today
  DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
Calendar cal = Calendar.getInstance();
//System.out.println(df.format(cal.getTime()));
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbid1 = new javax.swing.JTextField();
        rbid2 = new javax.swing.JTextField();
        rmemid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rdayfine = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lrtotfine = new javax.swing.JLabel();
        btnrreturn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtrnote = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        btnfinedayok = new javax.swing.JButton();
        btnmemidok = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Member ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel2.setText("Book ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        rbid1.setText("jTextField1");
        jPanel1.add(rbid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 136, 30));

        rbid2.setText("jTextField1");
        jPanel1.add(rbid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 136, 30));

        rmemid.setText("jTextField1");
        rmemid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmemidActionPerformed(evt);
            }
        });
        jPanel1.add(rmemid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 136, 30));

        jLabel3.setText("Fine per Day");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        rdayfine.setText("jTextField1");
        jPanel1.add(rdayfine, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 136, 30));

        jLabel4.setText("Total Fine");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        lrtotfine.setText("jLabel5");
        jPanel1.add(lrtotfine, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 136, -1));

        btnrreturn.setText("RETURN");
        btnrreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrreturnActionPerformed(evt);
            }
        });
        jPanel1.add(btnrreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 120, 48));

        txtrnote.setColumns(20);
        txtrnote.setRows(5);
        jScrollPane1.setViewportView(txtrnote);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        jLabel6.setText("Note");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        btnfinedayok.setText("OK");
        btnfinedayok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfinedayokActionPerformed(evt);
            }
        });
        jPanel1.add(btnfinedayok, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 50, 30));

        btnmemidok.setText("OK");
        btnmemidok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmemidokActionPerformed(evt);
            }
        });
        jPanel1.add(btnmemidok, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 50, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 610, 340));

        jLabel5.setText("    RETURN BOOKS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 110, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnrreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrreturnActionPerformed
        // TODO add your handling code here:
        
        String memid = rmemid.getText();
        String book1 = rbid1.getText();
         String book2 = rbid2.getText();
          String dayfine =rdayfine.getText();
        String totfine = lrtotfine.getText();
        
        ReturnBooksModel rbm = new ReturnBooksModel( memid, book1, book2, dayfine, totfine);
        
         boolean successStatus = rbm.insertReturnBook();
        if (successStatus) {
            JOptionPane.showMessageDialog(this, "Successfully inserted to db");
           
            rmemid.setText("");
            rbid1.setText("");
            rbid2.setText("");
            rdayfine.setText("");
            lrtotfine.setText("N/A");
        } else {
            JOptionPane.showMessageDialog(this, "Error in inserting to db");
        }
        
        
        
        
        
    }//GEN-LAST:event_btnrreturnActionPerformed

    private void rmemidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmemidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rmemidActionPerformed

    private void btnmemidokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmemidokActionPerformed
            try {
                // TODO add your handling code here:
                String memid = rmemid.getText();
                String book1 = rbid1.getText();
                String book2 = rbid2.getText();
                String dayfine =rdayfine.getText();
                String totfine = lrtotfine.getText();
                
                ReturnBooksModel r1 = new ReturnBooksModel( memid, book1, book2, dayfine, totfine);
                r1.showBooks();
                
// showBooks();
            } catch (SQLException ex) {
                Logger.getLogger(ReturnBooks_UI.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        
    }//GEN-LAST:event_btnmemidokActionPerformed

    private void btnfinedayokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfinedayokActionPerformed
            try {
                // TODO add your handling code here:
                
                String memid = rmemid.getText();
                String book1 = rbid1.getText();
                String book2 = rbid2.getText();
                String dayfine =rdayfine.getText();
                String totfine = lrtotfine.getText();
                
                ReturnBooksModel r2 = new ReturnBooksModel( memid, book1, book2, dayfine, totfine);
                r2.calculateFine();
            } catch (SQLException ex) {
                Logger.getLogger(ReturnBooks_UI.class.getName()).log(Level.SEVERE, null, ex);
            }

        
    }//GEN-LAST:event_btnfinedayokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBooks_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBooks_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBooks_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBooks_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBooks_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfinedayok;
    private javax.swing.JButton btnmemidok;
    private javax.swing.JButton btnrreturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lrtotfine;
    private javax.swing.JTextField rbid1;
    private javax.swing.JTextField rbid2;
    private javax.swing.JTextField rdayfine;
    private javax.swing.JTextField rmemid;
    private javax.swing.JTextArea txtrnote;
    // End of variables declaration//GEN-END:variables
}
